import { Minimize2, PlexIcon, JellyfinIcon, KodiIcon } from '@/ui/icons';
import {
  EXTRAS_FOLDER_MODES,
  FOLDER_COLLECTION_MODES,
  SETTINGS_PRESET_IDS,
} from '@/lib/settingsConstants';

const ADULT_SUBFOLDER_PRESET = {
  naming_adult_subfolders_enabled: true,
  folder_adult_movies_name: 'Movies',
  folder_adult_tv_name: 'TV Shows',
  folder_adult_scenes_name: 'Scenes',
  folder_adult_videos_name: 'Videos',
};

const ADULT_STANDARD_PRESET = {
  ...ADULT_SUBFOLDER_PRESET,
  naming_scene_template: '{studio} - {date} - {performers} - {title} [{resolution}]',
  naming_scene_date_format: '%Y-%m-%d',
  naming_scene_prevent_title_performer: true,
  scene_tag_limit: '0',
  scene_tag_separator: ' ',
  scene_tag_blacklist: '',
  naming_squeeze_studio_names: false,
  naming_performer_limit: '3',
  naming_performer_limit_keep: true,
  naming_performer_splitchar: ' & ',
  naming_performer_gender_filter: 'all',
  naming_performer_sort: 'popularity',
  scene_grouping_mode: 'parent_studio_studio',
  folder_create_scene_subdir: true,
  folder_scene_template: '{date} - {title}',
};

const ADULT_MINIMAL_PRESET = {
  ...ADULT_SUBFOLDER_PRESET,
  naming_scene_template: '{date} - {performers} - {title}',
  naming_scene_date_format: '%Y-%m-%d',
  naming_scene_prevent_title_performer: true,
  scene_tag_limit: '0',
  scene_tag_separator: ' ',
  scene_tag_blacklist: '',
  naming_squeeze_studio_names: false,
  naming_performer_limit: '3',
  naming_performer_limit_keep: true,
  naming_performer_splitchar: ' & ',
  naming_performer_gender_filter: 'all',
  naming_performer_sort: 'popularity',
  scene_grouping_mode: 'none',
  folder_create_scene_subdir: false,
  folder_scene_template: '',
};

export const PRESETS_CONFIG = {
  [SETTINGS_PRESET_IDS.PLEX]: {
    ...ADULT_STANDARD_PRESET,
    naming_filename_casing: 'default',
    naming_word_separator: 'space',
    naming_movie_template: '{title} ({year}) {resolution}',
    naming_episode_template: '{tv_title} - S{season}E{episode} - {episode_title}',
    folder_create_movie_subdir: true,
    folder_movie_template: '{title} ({year})',
    folder_create_show_dir: true,
    folder_tv_template: '{tv_title} ({year_range})',
    folder_create_video_subdir: true,
    folder_videos_name: 'Videos',
    folder_create_season_dir: true,
    folder_season_template: 'Season {season}',
    folder_create_episode_dir: false,
    folder_episode_template: '{tv_title} - {season}{episode}',
    folder_create_collection_dir: true,
    folder_collection_mode: FOLDER_COLLECTION_MODES.THRESHOLD,
    extras_folder_mode: EXTRAS_FOLDER_MODES.SUBFOLDER,
    extras_subfolder_name: 'Extras',
  },
  [SETTINGS_PRESET_IDS.JELLYFIN]: {
    ...ADULT_STANDARD_PRESET,
    naming_filename_casing: 'default',
    naming_word_separator: 'space',
    naming_movie_template: '{title} ({year}) {resolution}',
    naming_episode_template: '{tv_title} - S{season}E{episode} - {episode_title}',
    folder_create_movie_subdir: true,
    folder_movie_template: '{title} ({year})',
    folder_create_show_dir: true,
    folder_tv_template: '{tv_title} ({year_range})',
    folder_create_video_subdir: true,
    folder_videos_name: 'Videos',
    folder_create_season_dir: true,
    folder_season_template: 'Season {season}',
    folder_create_episode_dir: false,
    folder_episode_template: '{tv_title} - {season}{episode}',
    folder_create_collection_dir: true,
    folder_collection_mode: FOLDER_COLLECTION_MODES.THRESHOLD,
    extras_folder_mode: EXTRAS_FOLDER_MODES.FLAT,
    extras_subfolder_name: 'Extras',
  },
  [SETTINGS_PRESET_IDS.KODI]: {
    ...ADULT_STANDARD_PRESET,
    naming_filename_casing: 'default',
    naming_word_separator: 'dot',
    naming_movie_template: '{title} ({year}) {resolution}',
    naming_episode_template: '{tv_title} - S{season}E{episode} - {episode_title}',
    folder_create_movie_subdir: true,
    folder_movie_template: '{title} ({year})',
    folder_create_show_dir: true,
    folder_tv_template: '{tv_title} ({year_range})',
    folder_create_video_subdir: true,
    folder_videos_name: 'Videos',
    folder_create_season_dir: true,
    folder_season_template: 'Season {season}',
    folder_create_episode_dir: false,
    folder_episode_template: '{tv_title} - {season}{episode}',
    folder_create_collection_dir: true,
    folder_collection_mode: FOLDER_COLLECTION_MODES.THRESHOLD,
    extras_folder_mode: EXTRAS_FOLDER_MODES.FLAT,
    extras_subfolder_name: 'Extras',
  },
  [SETTINGS_PRESET_IDS.MINIMAL]: {
    ...ADULT_MINIMAL_PRESET,
    naming_filename_casing: 'default',
    naming_word_separator: 'space',
    naming_movie_template: '{title} ({year})',
    naming_episode_template: '{tv_title} S{season}E{episode}',
    folder_create_movie_subdir: false,
    folder_movie_template: '{title} ({year})',
    folder_create_show_dir: true,
    folder_tv_template: '{tv_title}',
    folder_create_video_subdir: false,
    folder_videos_name: 'Videos',
    folder_create_season_dir: false,
    folder_season_template: 'Season {season}',
    folder_create_episode_dir: false,
    folder_episode_template: '{tv_title} - {season}{episode}',
    folder_create_collection_dir: false,
    folder_collection_mode: FOLDER_COLLECTION_MODES.NEVER,
    extras_folder_mode: EXTRAS_FOLDER_MODES.FLAT,
    extras_subfolder_name: 'Extras',
  }
};

export function getPresetCards(t) {
  return [
    {
      value: SETTINGS_PRESET_IDS.PLEX,
      label: t('settingsPage.sections.organization.presets.plex') || 'Plex Standard',
      desc: t('settingsPage.sections.organization.presets.plexDesc') || 'Plex-style naming with Adult/Movies, Adult/TV Shows, and studio-grouped Adult/Scenes.',
      icon: PlexIcon,
    },
    {
      value: SETTINGS_PRESET_IDS.JELLYFIN,
      label: t('settingsPage.sections.organization.presets.jellyfin') || 'Jellyfin Standard',
      desc: t('settingsPage.sections.organization.presets.jellyfinDesc') || 'Jellyfin-friendly naming with Adult/Movies, Adult/TV Shows, and studio-grouped Adult/Scenes.',
      icon: JellyfinIcon,
    },
    {
      value: SETTINGS_PRESET_IDS.KODI,
      label: t('settingsPage.sections.organization.presets.kodi') || 'Kodi Standard',
      desc: t('settingsPage.sections.organization.presets.kodiDesc') || 'Kodi-friendly dot naming with Adult/Movies, Adult/TV Shows, and studio-grouped Adult/Scenes.',
      icon: KodiIcon,
    },
    {
      value: SETTINGS_PRESET_IDS.MINIMAL,
      label: t('settingsPage.sections.organization.presets.minimal') || 'Minimalist Layout',
      desc: t('settingsPage.sections.organization.presets.minimalDesc') || 'A shallow layout that still separates Adult/Movies, Adult/TV Shows, and Adult/Scenes.',
      icon: Minimize2,
      iconColor: 'var(--brand-minimal)',
    }
  ];
}
