import { fetchJson } from '../../http';
import { FOLDER_COLLECTION_MODES } from '@/lib/settingsConstants';

const toNonNegativeNumber = (value, fallback) => {
  const parsed = Number.parseFloat(value);
  return Number.isFinite(parsed) ? Math.max(0, parsed) : fallback;
};

export const buildSettingsPayload = (form) => ({
  user_name: (form.user_name || '').trim(),
  avatar_path: form.avatar_path || '',
  default_scan_dir: (form.default_scan_dir || '').trim(),
  folder_library_path: (form.folder_library_path || '').trim(),
  folder_adult_library_path: (form.folder_adult_library_path || '').trim(),
  naming_adult_movie_template: (form.naming_adult_movie_template || '').trim(),
  folder_adult_movie_template: (form.folder_adult_movie_template || '').trim(),
  naming_adult_episode_template: (form.naming_adult_episode_template || '').trim(),
  folder_adult_tv_template: (form.folder_adult_tv_template || '').trim(),
  folder_adult_season_template: (form.folder_adult_season_template || '').trim(),
  collision_strategy: form.collision_strategy,
  collision_duration_tolerance_seconds: String(form.collision_duration_tolerance_seconds || '10').trim(),
  extras_video_action: form.extras_video_action,
  extras_sub_action: form.extras_sub_action,
  extras_audio_action: form.extras_audio_action,
  extras_img_action: form.extras_img_action,
  extras_meta_action: form.extras_meta_action,
  vlc_path: (form.vlc_path || '').trim(),
  mpc_path: (form.mpc_path || '').trim(),
  preferred_player: form.preferred_player,
  player_preferred_audio_language: form.player_preferred_audio_language || 'none',
  player_preferred_subtitle_language: form.player_preferred_subtitle_language || 'none',
  player_subtitle_mode: form.player_subtitle_mode || 'off_with_matching_audio',
  tmdb_api_key: (form.tmdb_api_key || '').trim(),
  tmdb_bearer_token: (form.tmdb_bearer_token || '').trim(),
  omdb_api_key: (form.omdb_api_key || '').trim(),
  ui_language: form.ui_language,
  follow_app_language_for_media_library: form.follow_app_language_for_media_library,
  follow_app_language_for_naming: form.follow_app_language_for_naming,
  primary_metadata_language: form.follow_app_language_for_media_library
    ? (form.ui_language === 'en' ? 'en-US' : form.ui_language)
    : form.primary_metadata_language,
  fallback_metadata_language: form.fallback_metadata_language,
  default_target_language: form.follow_app_language_for_naming
    ? form.ui_language
    : form.default_target_language,
  close_button_behavior: form.close_button_behavior,
  include_adult: form.include_adult,
  adult_gender_preference: form.adult_gender_preference,
  stashdb_api_key: (form.stashdb_api_key || '').trim(),
  fansdb_api_key: (form.fansdb_api_key || '').trim(),
  theporndb_api_key: (form.theporndb_api_key || '').trim(),
  stashdb_endpoint: (form.stashdb_endpoint || '').trim(),
  fansdb_endpoint: (form.fansdb_endpoint || '').trim(),
  theporndb_endpoint: (form.theporndb_endpoint || '').trim(),
  custom_organization_enabled: form.custom_organization_enabled,
  organization_preset: form.organization_preset,
  ui_theme: form.ui_theme,
  min_video_size_mb: parseInt(form.min_video_size_mb, 10) || 50,
  min_video_duration_minutes: parseInt(form.min_video_duration_minutes, 10) || 12,
  adult_min_video_size_mb: toNonNegativeNumber(form.adult_min_video_size_mb, 1),
  adult_min_video_duration_minutes: toNonNegativeNumber(form.adult_min_video_duration_minutes, 1.0),
  fansdb_adult_min_video_duration_minutes: toNonNegativeNumber(form.fansdb_adult_min_video_duration_minutes, 0.14),
  folder_create_collection_dir: form.folder_create_collection_dir,
  folder_collection_mode: form.folder_create_collection_dir
    ? form.folder_collection_mode
    : FOLDER_COLLECTION_MODES.NEVER,
  folder_collection_threshold: parseInt(form.folder_collection_threshold, 10) || 3,
  naming_performer_splitchar: form.naming_performer_splitchar,
  naming_performer_gender_filter: form.naming_performer_gender_filter,
  naming_performer_sort: form.naming_performer_sort,
  scene_grouping_mode: form.scene_grouping_mode,
  folder_create_scene_subdir: form.folder_create_scene_subdir,
  folder_scene_template: (form.folder_scene_template || '').trim(),
  naming_custom_tag: (form.naming_custom_tag || '').trim(),
  naming_video_exts: (form.naming_video_exts || '').trim(),
  folder_organization_enabled: form.folder_organization_enabled,
  folder_move_to_library: form.folder_move_to_library,
  folder_sort_by_type: form.folder_sort_by_type,
  folder_movies_name: (form.folder_movies_name || '').trim(),
  folder_tv_name: (form.folder_tv_name || '').trim(),
  folder_videos_name: (form.folder_videos_name || '').trim(),
  folder_adult_name: (form.folder_adult_name || '').trim(),
  naming_adult_subfolders_enabled: form.naming_adult_subfolders_enabled,
  folder_adult_movies_name: (form.folder_adult_movies_name || '').trim(),
  folder_adult_tv_name: (form.folder_adult_tv_name || '').trim(),
  folder_adult_scenes_name: (form.folder_adult_scenes_name || '').trim(),
  folder_adult_videos_name: (form.folder_adult_videos_name || '').trim(),
  folder_create_movie_subdir: form.folder_create_movie_subdir,
  folder_movie_template: (form.folder_movie_template || '').trim(),
  folder_create_show_dir: form.folder_create_show_dir,
  folder_tv_template: (form.folder_tv_template || '').trim(),
  folder_create_video_subdir: form.folder_create_video_subdir,
  folder_create_season_dir: form.folder_create_season_dir,
  folder_season_template: (form.folder_season_template || '').trim(),
  folder_create_episode_dir: form.folder_create_episode_dir,
  folder_episode_template: (form.folder_episode_template || '').trim(),
  folder_remove_empty: form.folder_remove_empty,
  folder_collection_template: (form.folder_collection_template || '').trim(),
  extras_enabled: form.extras_enabled,
  extras_sub_exts: (form.extras_sub_exts || '').trim(),
  extras_audio_exts: (form.extras_audio_exts || '').trim(),
  extras_img_exts: (form.extras_img_exts || '').trim(),
  extras_meta_exts: (form.extras_meta_exts || '').trim(),
  extras_video_template: (form.extras_video_template || '').trim(),
  extras_sub_template: (form.extras_sub_template || '').trim(),
  extras_audio_template: (form.extras_audio_template || '').trim(),
  extras_img_template: (form.extras_img_template || '').trim(),
  extras_meta_template: (form.extras_meta_template || '').trim(),
  extras_folder_mode: form.extras_folder_mode,
  extras_subfolder_name: (form.extras_subfolder_name || '').trim(),
  scenes_scraper_order: form.scenes_scraper_order,
  naming_filename_casing: form.naming_filename_casing,
  naming_word_separator: form.naming_word_separator,
  naming_movie_template: (form.naming_movie_template || '').trim(),
  naming_episode_template: (form.naming_episode_template || '').trim(),
  naming_scene_template: (form.naming_scene_template || '').trim(),
  naming_jav_template: (form.naming_jav_template || '').trim(),
  naming_scene_date_format: (form.naming_scene_date_format || '').trim(),
  naming_scene_prevent_title_performer: form.naming_scene_prevent_title_performer,
  scene_tag_limit: Math.max(0, parseInt(form.scene_tag_limit, 10) || 0),
  scene_tag_separator: form.scene_tag_separator,
  scene_tag_blacklist: (form.scene_tag_blacklist || '').trim(),
  naming_squeeze_studio_names: form.naming_squeeze_studio_names,
  naming_performer_limit: Math.max(1, parseInt(form.naming_performer_limit, 10) || 3),
  naming_performer_limit_keep: form.naming_performer_limit_keep,
  jav_grouping_mode: form.jav_grouping_mode,
  folder_jav_template: (form.folder_jav_template || '').trim(),
  folder_adult_jav_name: (form.folder_adult_jav_name || '').trim(),
  adult_tag_blacklist: (form.adult_tag_blacklist || '').trim(),
  adult_stashdb_focus_tag: (form.adult_stashdb_focus_tag || '').trim(),
  adult_fansdb_focus_tag: (form.adult_fansdb_focus_tag || '').trim(),
  torrent_enabled: Boolean(form.torrent_enabled),
  torrent_download_dir: (form.torrent_download_dir || '').trim(),
  torrent_qbittorrent_port: String(form.torrent_qbittorrent_port || '8080').trim(),
  torrent_qbittorrent_user: String(form.torrent_qbittorrent_user || 'admin').trim(),
  torrent_qbittorrent_pass: String(form.torrent_qbittorrent_pass || 'adminadmin').trim(),
  hover_previews_enabled: Boolean(form.hover_previews_enabled),
  hover_previews_delay: parseInt(form.hover_previews_delay, 10) || 800,
  hover_previews_duration: parseInt(form.hover_previews_duration, 10) || 16,
  previews_cache_max_size_mb: parseInt(form.previews_cache_max_size_mb, 10) || 2048,
  previews_cache_max_age_days: parseInt(form.previews_cache_max_age_days, 10) || 30,
});

export const settingsPersistenceApi = {
  get: () => fetchJson('/api/settings'),
  import: (settings) => fetchJson('/api/settings/import', {
    method: 'POST',
    body: JSON.stringify(settings),
  }),
  update: (settings) => fetchJson('/api/settings', {
    method: 'POST',
    body: JSON.stringify(settings),
  }),
  clearDatabase: (options) => fetchJson('/api/database/clear', {
    method: 'POST',
    body: JSON.stringify(options),
  }),
};
