import { useMemo } from 'react';
import { getTabDefinition, getVisibleOrganizationTabs, getVisibleAdultTabs } from '../config';

export default function useSettingsRenderContext({
  t,
  form,
  setForm,
  isSaving,
  isWiping,
  isScanActive,
  isBackgroundActive,
  isSyncActive,
  validationErrors,
  formInputs,
  insertTag,
  handleChange,
  handleCheckboxChange,
  handlePickFolder,
  handlePickFile,
  handleExportSettings,
  handleImportClick,
  handleImportSettings,
  handleResetToDefaults,
  handleWipeDatabase,
  isWipingCache,
  handleWipeCache,
  handleSyncLanguage,
  isSyncingLanguage,
  activeTab,
  optionContext,
}) {
  const renderContext = useMemo(() => ({
    t,
    form,
    setForm,
    isSaving,
    isWiping,
    isWipingCache,
    isScanActive,
    isBackgroundActive: false,
    realBackgroundActive: isBackgroundActive,
    isSyncActive,
    isSyncingLanguage,
    validationErrors,
    formInputs,
    insertTag,
    handleChange,
    handleCheckboxChange,
    handlePickFolder,
    handlePickFile,
    handleExportSettings,
    handleImportClick,
    handleImportSettings,
    handleResetToDefaults,
    handleWipeDatabase,
    handleWipeCache,
    handleSyncLanguage,
    activeTab,
    ...optionContext,
  }), [
    t,
    form,
    setForm,
    isSaving,
    isWiping,
    isWipingCache,
    isScanActive,
    isBackgroundActive,
    isSyncActive,
    isSyncingLanguage,
    validationErrors,
    formInputs,
    insertTag,
    handleChange,
    handleCheckboxChange,
    handlePickFolder,
    handlePickFile,
    handleExportSettings,
    handleImportClick,
    handleImportSettings,
    handleResetToDefaults,
    handleWipeDatabase,
    handleWipeCache,
    handleSyncLanguage,
    activeTab,
    optionContext,
  ]);

  const visibleOrganizationTabs = useMemo(() => getVisibleOrganizationTabs(renderContext), [renderContext]);
  const visibleAdultTabs = useMemo(() => getVisibleAdultTabs(renderContext), [renderContext]);
  const activeTabDefinition = useMemo(() => getTabDefinition(activeTab), [activeTab]);

  const formContextActions = useMemo(() => ({
    handleChange,
    handleCheckboxChange,
    handlePickFolder,
    handlePickFile,
    insertTag,
  }), [handleChange, handleCheckboxChange, handlePickFolder, handlePickFile, insertTag]);

  return {
    renderContext,
    visibleOrganizationTabs,
    visibleAdultTabs,
    activeTabDefinition,
    formContextActions,
  };
}
